/**
 * Comprehensive Power-Up & Ability Catalogue for Pencil Flow
 * 50 distinct conceptual abilities across 10 functional categories.
 */

export type PowerUpCategory =
  | 'MOVEMENT'
  | 'DEFENSE'
  | 'SCORING'
  | 'DRAWING'
  | 'WORLD_MANIPULATION'
  | 'TIME'
  | 'RISK_REWARD'
  | 'COLLECTING'
  | 'COMBO'
  | 'SPECIAL';

export type PowerUpRarity = 'COMMON' | 'RARE' | 'EPIC' | 'LEGENDARY';

export interface PowerUpDefinition {
  id: string;
  name: string;
  codeName: string;
  category: PowerUpCategory;
  rarity: PowerUpRarity;
  desc: string;
  shortDesc: string;
  duration: number; // In seconds (0 = instant)
  colorHex: string;
  emissiveHex: string;
  iconSymbol: string;
  basePrice: number;
  priceCurrency: 'GRAPHITE' | 'LEAD';
  upgradeLevels: number;
  unlockedByDefault: boolean;
}

export const POWER_UP_CATALOGUE: Record<string, PowerUpDefinition> = {
  // ==========================================
  // 1. MOVEMENT (1-7)
  // ==========================================
  speed_boost: {
    id: 'speed_boost',
    name: '2B Graphite Surge',
    codeName: 'SURGE',
    category: 'MOVEMENT',
    rarity: 'RARE',
    desc: 'Supercharges graphite rolling velocity by +35% with dynamic smoke trails.',
    shortDesc: '+35% Velocity & Trail Burst',
    duration: 5.5,
    colorHex: '#dfab34',
    emissiveHex: '#d97706',
    iconSymbol: '⚡',
    basePrice: 200,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: true,
  },
  air_dash: {
    id: 'air_dash',
    name: 'Acrobatic Air Dash',
    codeName: 'AIR_DASH',
    category: 'MOVEMENT',
    rarity: 'RARE',
    desc: 'Propels the ball forward mid-air with extended hangtime over hazards.',
    shortDesc: 'Forward leap over hazard gaps',
    duration: 0,
    colorHex: '#38bdf8',
    emissiveHex: '#0284c7',
    iconSymbol: '彡',
    basePrice: 350,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  slow_reflex: {
    id: 'slow_reflex',
    name: 'Draftsman Reflex',
    codeName: 'SLOW_REFLEX',
    category: 'MOVEMENT',
    rarity: 'COMMON',
    desc: 'Dilates perception when near hazards, giving precise steering control.',
    shortDesc: 'Micro-slowdown near obstacles',
    duration: 6.0,
    colorHex: '#06d6a0',
    emissiveHex: '#059669',
    iconSymbol: '⏱',
    basePrice: 180,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: true,
  },
  emergency_brake: {
    id: 'emergency_brake',
    name: 'Graphite Friction Brake',
    codeName: 'BRAKE',
    category: 'MOVEMENT',
    rarity: 'COMMON',
    desc: 'Immediately drops speed to baseline safety for surgical obstacle navigation.',
    shortDesc: 'Instant recovery to cruising speed',
    duration: 3.5,
    colorHex: '#f59e0b',
    emissiveHex: '#b45309',
    iconSymbol: '🛑',
    basePrice: 150,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },
  lane_snap: {
    id: 'lane_snap',
    name: 'T-Square Lane Snap',
    codeName: 'LANE_SNAP',
    category: 'MOVEMENT',
    rarity: 'COMMON',
    desc: 'Snaps lateral position instantly to lane centerlines without drift.',
    shortDesc: 'Magnetic lane locking',
    duration: 8.0,
    colorHex: '#60a5fa',
    emissiveHex: '#2563eb',
    iconSymbol: '⤧',
    basePrice: 220,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  momentum_lock: {
    id: 'momentum_lock',
    name: 'Flywheel Momentum',
    codeName: 'MOMENTUM',
    category: 'MOVEMENT',
    rarity: 'EPIC',
    desc: 'Locks speed at maximum cruising velocity without slowing down on curves.',
    shortDesc: 'Inertia lock through steep bends',
    duration: 7.0,
    colorHex: '#a855f7',
    emissiveHex: '#7e22ce',
    iconSymbol: '⚙',
    basePrice: 8,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  dash_charge: {
    id: 'dash_charge',
    name: 'Lead Spring Charger',
    codeName: 'DASH_CHARGE',
    category: 'MOVEMENT',
    rarity: 'RARE',
    desc: 'Charges kinetic energy during turns, releasing a speed boost on straightaways.',
    shortDesc: 'Turn-exit speed propulsion',
    duration: 7.5,
    colorHex: '#fb923c',
    emissiveHex: '#c2410c',
    iconSymbol: '⇶',
    basePrice: 420,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },

  // ==========================================
  // 2. DEFENSE (8-14)
  // ==========================================
  sketch_shield: {
    id: 'sketch_shield',
    name: 'Hard Eraser Shield',
    codeName: 'SHIELD',
    category: 'DEFENSE',
    rarity: 'RARE',
    desc: 'Absorbs one collision with an obstacle, shattering it into graphite dust.',
    shortDesc: 'Blocks 1 collision impact',
    duration: 12.0,
    colorHex: '#f43f5e',
    emissiveHex: '#be123c',
    iconSymbol: '🛡',
    basePrice: 300,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: true,
  },
  ghost_mode: {
    id: 'ghost_mode',
    name: 'Tracing Paper Ghost',
    codeName: 'GHOST',
    category: 'DEFENSE',
    rarity: 'EPIC',
    desc: 'Translucent vellum phase: pass directly through all track obstacles.',
    shortDesc: 'Phase through obstacles safely',
    duration: 5.0,
    colorHex: '#e2e8f0',
    emissiveHex: '#94a3b8',
    iconSymbol: '👻',
    basePrice: 12,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  obstacle_eraser: {
    id: 'obstacle_eraser',
    name: 'Kneaded Putty Eraser',
    codeName: 'ERASER',
    category: 'DEFENSE',
    rarity: 'RARE',
    desc: 'Erases all upcoming obstacles within 35 meters in a flash of white paper.',
    shortDesc: 'Wipes nearby obstacles',
    duration: 0,
    colorHex: '#ec4899',
    emissiveHex: '#be185d',
    iconSymbol: '⌦',
    basePrice: 380,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },
  obstacle_phase: {
    id: 'obstacle_phase',
    name: 'Isometric Phase',
    codeName: 'PHASE',
    category: 'DEFENSE',
    rarity: 'EPIC',
    desc: 'Converts all solid obstacles ahead into transparent wireframe silhouettes.',
    shortDesc: 'Converts hazards into wireframe',
    duration: 6.5,
    colorHex: '#00f0ff',
    emissiveHex: '#0284c7',
    iconSymbol: '◇',
    basePrice: 10,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  second_chance: {
    id: 'second_chance',
    name: 'Pencil Undo',
    codeName: 'UNDO',
    category: 'DEFENSE',
    rarity: 'LEGENDARY',
    desc: 'Instantly rewinds track position 20 meters backwards upon fatal fall or impact.',
    shortDesc: 'Auto-revive on fatal collision',
    duration: 0,
    colorHex: '#e11d48',
    emissiveHex: '#881337',
    iconSymbol: '↺',
    basePrice: 25,
    priceCurrency: 'LEAD',
    upgradeLevels: 1,
    unlockedByDefault: false,
  },
  safe_lane: {
    id: 'safe_lane',
    name: 'Architect Corridor',
    codeName: 'SAFE_LANE',
    category: 'DEFENSE',
    rarity: 'COMMON',
    desc: 'Highlights an obstacle-free guidance runway in luminous yellow chalk.',
    shortDesc: 'Guarantees clear passage corridor',
    duration: 9.0,
    colorHex: '#facc15',
    emissiveHex: '#a16207',
    iconSymbol: '║',
    basePrice: 200,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  invulnerability: {
    id: 'invulnerability',
    name: 'Tempered 9H Carbon Core',
    codeName: 'TEMPERED',
    category: 'DEFENSE',
    rarity: 'LEGENDARY',
    desc: 'Complete invulnerability: smash through obstacles and earn bonus destruction score.',
    shortDesc: 'Smash hazards with impunity',
    duration: 6.0,
    colorHex: '#ffffff',
    emissiveHex: '#d4d4d8',
    iconSymbol: '★',
    basePrice: 30,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },

  // ==========================================
  // 3. SCORING (15-20)
  // ==========================================
  score_mult: {
    id: 'score_mult',
    name: 'Gilded 2X Ink Multiplier',
    codeName: '2X_SCORE',
    category: 'SCORING',
    rarity: 'COMMON',
    desc: 'Doubles all score accumulation and distance metrics for the duration.',
    shortDesc: '2X Score accumulation',
    duration: 10.0,
    colorHex: '#f59e0b',
    emissiveHex: '#d97706',
    iconSymbol: '2×',
    basePrice: 240,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: true,
  },
  combo_saver: {
    id: 'combo_saver',
    name: 'Graphite Resonance Lock',
    codeName: 'COMBO_LOCK',
    category: 'SCORING',
    rarity: 'RARE',
    desc: 'Freezes combo multiplier timer so your high multiplier never resets.',
    shortDesc: 'Prevents combo decay',
    duration: 8.0,
    colorHex: '#8b5cf6',
    emissiveHex: '#6d28d9',
    iconSymbol: '🔒',
    basePrice: 320,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  near_miss_mult: {
    id: 'near_miss_mult',
    name: 'Precision Close-Call Booster',
    codeName: 'NEAR_MISS',
    category: 'SCORING',
    rarity: 'RARE',
    desc: 'Triple score awarded for close calls and brush dodges.',
    shortDesc: '3X Score for near-miss dodges',
    duration: 9.0,
    colorHex: '#10b981',
    emissiveHex: '#047857',
    iconSymbol: '🎯',
    basePrice: 360,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  chain_mult: {
    id: 'chain_mult',
    name: 'Cadence Shading Chain',
    codeName: 'CHAIN',
    category: 'SCORING',
    rarity: 'EPIC',
    desc: 'Every consecutive dodge rapidly increments your combo multiplier by +2.',
    shortDesc: '+2 Multiplier per dodge',
    duration: 7.0,
    colorHex: '#6366f1',
    emissiveHex: '#4338ca',
    iconSymbol: '⛓',
    basePrice: 12,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  score_bank: {
    id: 'score_bank',
    name: 'Vault of Sketches',
    codeName: 'SCORE_BANK',
    category: 'SCORING',
    rarity: 'EPIC',
    desc: 'Banks current score into permanent XP reserves, safe from run penalties.',
    shortDesc: 'Secures score into XP',
    duration: 0,
    colorHex: '#eab308',
    emissiveHex: '#ca8a04',
    iconSymbol: '🏦',
    basePrice: 15,
    priceCurrency: 'LEAD',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },
  jackpot: {
    id: 'jackpot',
    name: 'Golden Quill Bounty',
    codeName: 'JACKPOT',
    category: 'SCORING',
    rarity: 'LEGENDARY',
    desc: 'Spawns an explosive cascade of 40 golden graphite shards across the runway.',
    shortDesc: 'Spawns 40 gold shards',
    duration: 0,
    colorHex: '#fbbf24',
    emissiveHex: '#b45309',
    iconSymbol: '💰',
    basePrice: 40,
    priceCurrency: 'LEAD',
    upgradeLevels: 1,
    unlockedByDefault: false,
  },

  // ==========================================
  // 4. DRAWING (21-27)
  // ==========================================
  drawing_surge: {
    id: 'drawing_surge',
    name: 'Maestro Drawing Surge',
    codeName: 'SURGE_DRAW',
    category: 'DRAWING',
    rarity: 'EPIC',
    desc: 'Pencils sketch at 3X velocity with intense cross-hatching and sparkling linework.',
    shortDesc: 'Pencils sketch at 3X speed',
    duration: 8.0,
    colorHex: '#38bdf8',
    emissiveHex: '#0284c7',
    iconSymbol: '✎',
    basePrice: 14,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  pencil_clone: {
    id: 'pencil_clone',
    name: 'Apprentice Pencil Clones',
    codeName: 'CLONE',
    category: 'DRAWING',
    rarity: 'LEGENDARY',
    desc: 'Summons two additional satellite drawing pencils to flank your path.',
    shortDesc: 'Summons dual auxiliary pencils',
    duration: 10.0,
    colorHex: '#c084fc',
    emissiveHex: '#9333ea',
    iconSymbol: '✏✏',
    basePrice: 35,
    priceCurrency: 'LEAD',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },
  road_repair: {
    id: 'road_repair',
    name: 'Rapid Drafting Fill',
    codeName: 'REPAIR',
    category: 'DRAWING',
    rarity: 'RARE',
    desc: 'Instantly widens and banks the track shoulders by +40% with reinforced curbs.',
    shortDesc: 'Widens track runway by +40%',
    duration: 8.5,
    colorHex: '#4ade80',
    emissiveHex: '#16a34a',
    iconSymbol: '▤',
    basePrice: 340,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  road_stabilizer: {
    id: 'road_stabilizer',
    name: 'Steel Ruler Straightener',
    codeName: 'STABILIZER',
    category: 'DRAWING',
    rarity: 'COMMON',
    desc: 'Locks track curvature into a dead-straight high-speed boulevard.',
    shortDesc: 'Straightens track ahead',
    duration: 7.0,
    colorHex: '#94a3b8',
    emissiveHex: '#475569',
    iconSymbol: '📏',
    basePrice: 190,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: true,
  },
  double_trail: {
    id: 'double_trail',
    name: 'Dual Charcoal Smudge',
    codeName: 'DOUBLE_TRAIL',
    category: 'DRAWING',
    rarity: 'COMMON',
    desc: 'Emits dense carbon shading trails behind the ball that magnetize shards.',
    shortDesc: 'Wide magnetic sketch trail',
    duration: 9.0,
    colorHex: '#475569',
    emissiveHex: '#1e293b',
    iconSymbol: '≋',
    basePrice: 210,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  extended_lead: {
    id: 'extended_lead',
    name: 'Far-Sight Lead Extension',
    codeName: 'EXTENDED_LEAD',
    category: 'DRAWING',
    rarity: 'RARE',
    desc: 'Pushes the forward pencil 80 meters ahead for ultimate hazard previewing.',
    shortDesc: 'Draws 80m further ahead',
    duration: 10.0,
    colorHex: '#0284c7',
    emissiveHex: '#0369a1',
    iconSymbol: '🔭',
    basePrice: 280,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  env_boost: {
    id: 'env_boost',
    name: 'Landscape Atelier',
    codeName: 'ATELIER',
    category: 'DRAWING',
    rarity: 'RARE',
    desc: 'Side pencils sketch lush architectural groves and pavilions alongside the track.',
    shortDesc: 'Enriches roadside architecture',
    duration: 8.0,
    colorHex: '#14b8a6',
    emissiveHex: '#0f766e',
    iconSymbol: '🏛',
    basePrice: 320,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },

  // ==========================================
  // 5. WORLD MANIPULATION (28-33)
  // ==========================================
  world_reveal: {
    id: 'world_reveal',
    name: 'Architectural Blueprint Reveal',
    codeName: 'REVEAL',
    category: 'WORLD_MANIPULATION',
    rarity: 'EPIC',
    desc: 'Lifts world fog and renders the distant skyline in crisp CAD linework.',
    shortDesc: 'Eliminates fog across the horizon',
    duration: 11.0,
    colorHex: '#38bdf8',
    emissiveHex: '#0284c7',
    iconSymbol: '☼',
    basePrice: 11,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  time_freeze: {
    id: 'time_freeze',
    name: 'Still Life Time Freeze',
    codeName: 'FREEZE',
    category: 'WORLD_MANIPULATION',
    rarity: 'EPIC',
    desc: 'Freezes moving obstacles, swinging pendulums, and hazards in place.',
    shortDesc: 'Freezes moving hazards',
    duration: 6.0,
    colorHex: '#06b6d4',
    emissiveHex: '#0891b2',
    iconSymbol: '❄',
    basePrice: 16,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  gravity_shift: {
    id: 'gravity_shift',
    name: 'Featherweight Vellum',
    codeName: 'LOW_GRAV',
    category: 'WORLD_MANIPULATION',
    rarity: 'COMMON',
    desc: 'Reduces ball gravity by 50%, enabling soaring jumps over entire clusters.',
    shortDesc: '50% Lower gravity for huge leaps',
    duration: 8.0,
    colorHex: '#ec4899',
    emissiveHex: '#be185d',
    iconSymbol: '🪶',
    basePrice: 220,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  hazard_scanner: {
    id: 'hazard_scanner',
    name: 'Redline Hazard Scanner',
    codeName: 'SCANNER',
    category: 'WORLD_MANIPULATION',
    rarity: 'COMMON',
    desc: 'Projects red warning cross-hairs over upcoming hazards 50m in advance.',
    shortDesc: 'Highlights hazards 50m out',
    duration: 12.0,
    colorHex: '#ef4444',
    emissiveHex: '#b91c1c',
    iconSymbol: '⌖',
    basePrice: 190,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: true,
  },
  path_preview: {
    id: 'path_preview',
    name: 'Topographic Contour Lines',
    codeName: 'CONTOUR',
    category: 'WORLD_MANIPULATION',
    rarity: 'RARE',
    desc: 'Draws fluorescent holographic elevation curves indicating upcoming hills.',
    shortDesc: 'Visualizes banking & drops ahead',
    duration: 10.0,
    colorHex: '#10b981',
    emissiveHex: '#059669',
    iconSymbol: '📈',
    basePrice: 280,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },
  daylight_shift: {
    id: 'daylight_shift',
    name: 'Solar Disc Flare',
    codeName: 'SOLAR',
    category: 'WORLD_MANIPULATION',
    rarity: 'RARE',
    desc: 'Illuminates the scene with radiant celestial compass rays, clearing shadows.',
    shortDesc: 'Solar flare illuminates hazards',
    duration: 9.0,
    colorHex: '#fde047',
    emissiveHex: '#ca8a04',
    iconSymbol: '☀',
    basePrice: 300,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },

  // ==========================================
  // 6. COLLECTING (34-40)
  // ==========================================
  graphite_magnet: {
    id: 'graphite_magnet',
    name: 'Graphite Shard Magnet',
    codeName: 'MAGNET',
    category: 'COLLECTING',
    rarity: 'COMMON',
    desc: 'Draws all nearby graphite shards directly toward the ball.',
    shortDesc: 'Attracts nearby graphite shards',
    duration: 8.5,
    colorHex: '#00f0ff',
    emissiveHex: '#0284c7',
    iconSymbol: '🧲',
    basePrice: 250,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: true,
  },
  double_collect: {
    id: 'double_collect',
    name: 'Alchemist Carbon Duplicator',
    codeName: 'DUPLICATOR',
    category: 'COLLECTING',
    rarity: 'RARE',
    desc: 'Every collected graphite shard counts as 2 units in your wallet.',
    shortDesc: '2X Shard value per pickup',
    duration: 9.0,
    colorHex: '#10b981',
    emissiveHex: '#047857',
    iconSymbol: '💎💎',
    basePrice: 380,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  collector_burst: {
    id: 'collector_burst',
    name: 'Centripetal Shard Nova',
    codeName: 'BURST',
    category: 'COLLECTING',
    rarity: 'RARE',
    desc: 'Instantly vacuums all visible collectibles across all lanes.',
    shortDesc: 'Wipes all visible shards instantly',
    duration: 0,
    colorHex: '#06b6d4',
    emissiveHex: '#0891b2',
    iconSymbol: '✦',
    basePrice: 320,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },
  powerup_magnet: {
    id: 'powerup_magnet',
    name: 'Lead Crystal Attractor',
    codeName: 'PU_MAGNET',
    category: 'COLLECTING',
    rarity: 'EPIC',
    desc: 'Bends the trajectories of upcoming power-ups directly into your lane.',
    shortDesc: 'Attracts power-up cores',
    duration: 10.0,
    colorHex: '#d946ef',
    emissiveHex: '#a21caf',
    iconSymbol: '⚡🧲',
    basePrice: 12,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  auto_collect: {
    id: 'auto_collect',
    name: 'Autonomous Drone Stylus',
    codeName: 'DRONE',
    category: 'COLLECTING',
    rarity: 'EPIC',
    desc: 'Dispatches a tiny quill that sweeps adjacent lanes to scoop up shards.',
    shortDesc: 'Sweeps outer lane collectibles',
    duration: 8.0,
    colorHex: '#38bdf8',
    emissiveHex: '#0284c7',
    iconSymbol: '✈',
    basePrice: 14,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  lead_finder: {
    id: 'lead_finder',
    name: '2B Lead Seeker',
    codeName: 'LEAD_FINDER',
    category: 'COLLECTING',
    rarity: 'LEGENDARY',
    desc: 'Guarantees the next power-up spawned is an Epic or Legendary ability.',
    shortDesc: 'Next power-up is Epic/Legendary',
    duration: 0,
    colorHex: '#eab308',
    emissiveHex: '#ca8a04',
    iconSymbol: '👑',
    basePrice: 30,
    priceCurrency: 'LEAD',
    upgradeLevels: 1,
    unlockedByDefault: false,
  },
  shard_transmute: {
    id: 'shard_transmute',
    name: 'Lead Synthesis Crucible',
    codeName: 'SYNTHESIS',
    category: 'COLLECTING',
    rarity: 'LEGENDARY',
    desc: 'Collecting 50 shards during this run permanently awards +1 2B Lead.',
    shortDesc: 'Converts 50 shards into 1 Lead',
    duration: 15.0,
    colorHex: '#f59e0b',
    emissiveHex: '#b45309',
    iconSymbol: '⚗',
    basePrice: 35,
    priceCurrency: 'LEAD',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },

  // ==========================================
  // 7. TIME & COMBO (41-46)
  // ==========================================
  slow_time: {
    id: 'slow_time',
    name: 'Chronograph Dilator',
    codeName: 'SLOW_TIME',
    category: 'TIME',
    rarity: 'RARE',
    desc: 'Slows entire world simulation to 50% speed while keeping steering snappy.',
    shortDesc: '50% Simulation speed slowdown',
    duration: 5.0,
    colorHex: '#0284c7',
    emissiveHex: '#0369a1',
    iconSymbol: '⌛',
    basePrice: 300,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: true,
  },
  combo_freeze: {
    id: 'combo_freeze',
    name: 'Rhythm Metronome',
    codeName: 'RHYTHM',
    category: 'COMBO',
    rarity: 'COMMON',
    desc: 'Locks combo multiplier at its peak value for 10 full seconds.',
    shortDesc: '10s Combo multiplier lock',
    duration: 10.0,
    colorHex: '#8b5cf6',
    emissiveHex: '#6d28d9',
    iconSymbol: '♩',
    basePrice: 220,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  perfect_landing_boost: {
    id: 'perfect_landing_boost',
    name: 'Trampoline Draft Paper',
    codeName: 'SPRING',
    category: 'COMBO',
    rarity: 'RARE',
    desc: 'Every jump landing generates an explosive sketch ripple awarding +250 XP.',
    shortDesc: 'Massive bonus on jump landings',
    duration: 8.0,
    colorHex: '#f43f5e',
    emissiveHex: '#be123c',
    iconSymbol: '☁',
    basePrice: 310,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  double_duration: {
    id: 'double_duration',
    name: 'Resin Fixative Spray',
    codeName: 'FIXATIVE',
    category: 'TIME',
    rarity: 'EPIC',
    desc: 'Extends the active duration of all current and upcoming power-ups by +50%.',
    shortDesc: '+50% Duration on all abilities',
    duration: 12.0,
    colorHex: '#14b8a6',
    emissiveHex: '#0f766e',
    iconSymbol: '🧪',
    basePrice: 15,
    priceCurrency: 'LEAD',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },
  time_bank: {
    id: 'time_bank',
    name: 'Hourglass of Da Vinci',
    codeName: 'HOURGLASS',
    category: 'TIME',
    rarity: 'EPIC',
    desc: 'Grants +5 seconds of slow motion whenever your speed crosses 28 u/s.',
    shortDesc: 'Auto slow-mo at hyper speed',
    duration: 12.0,
    colorHex: '#eab308',
    emissiveHex: '#ca8a04',
    iconSymbol: '⏳',
    basePrice: 14,
    priceCurrency: 'LEAD',
    upgradeLevels: 2,
    unlockedByDefault: false,
  },
  combo_frenzy: {
    id: 'combo_frenzy',
    name: 'Cadence Crescendo',
    codeName: 'FRENZY',
    category: 'COMBO',
    rarity: 'LEGENDARY',
    desc: 'Instantly escalates combo to max multiplier (x10) and triggers celebratory confetti.',
    shortDesc: 'Instantly caps combo at x10',
    duration: 6.0,
    colorHex: '#f59e0b',
    emissiveHex: '#d97706',
    iconSymbol: 'x10',
    basePrice: 35,
    priceCurrency: 'LEAD',
    upgradeLevels: 1,
    unlockedByDefault: false,
  },

  // ==========================================
  // 8. RISK / REWARD & SPECIAL (47-50)
  // ==========================================
  risk_mode: {
    id: 'risk_mode',
    name: 'Razor Blade Edge (High Risk)',
    codeName: 'RISK_MODE',
    category: 'RISK_REWARD',
    rarity: 'EPIC',
    desc: 'Narrows runway width by 25% but quadruples (4X) all score gains.',
    shortDesc: 'Narrow runway for 4X score',
    duration: 8.0,
    colorHex: '#ef4444',
    emissiveHex: '#991b1b',
    iconSymbol: '⚔',
    basePrice: 16,
    priceCurrency: 'LEAD',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  chaos_mode: {
    id: 'chaos_mode',
    name: 'Surrealist Dadaist Quill',
    codeName: 'CHAOS',
    category: 'SPECIAL',
    rarity: 'LEGENDARY',
    desc: 'Randomly cycles drawing styles every 3 seconds while granting invincibility!',
    shortDesc: 'Invincible wild style shifts',
    duration: 9.0,
    colorHex: '#ec4899',
    emissiveHex: '#be185d',
    iconSymbol: '🌀',
    basePrice: 45,
    priceCurrency: 'LEAD',
    upgradeLevels: 1,
    unlockedByDefault: false,
  },
  precision_mode: {
    id: 'precision_mode',
    name: '0.1mm Technical Caliper',
    codeName: 'PRECISION',
    category: 'SPECIAL',
    rarity: 'RARE',
    desc: 'Displays fine coordinate grid and grants ultra-tight lateral micro-steering.',
    shortDesc: 'Surgical micro-steering accuracy',
    duration: 9.0,
    colorHex: '#64748b',
    emissiveHex: '#334155',
    iconSymbol: '✛',
    basePrice: 320,
    priceCurrency: 'GRAPHITE',
    upgradeLevels: 3,
    unlockedByDefault: false,
  },
  rewind_pulse: {
    id: 'rewind_pulse',
    name: 'Graphite Chrono Erasure',
    codeName: 'REWIND',
    category: 'SPECIAL',
    rarity: 'LEGENDARY',
    desc: 'Rewinds player position smoothly backward along the path to re-collect missed items.',
    shortDesc: 'Safe loop backward for pickups',
    duration: 0,
    colorHex: '#6366f1',
    emissiveHex: '#4338ca',
    iconSymbol: '⏮',
    basePrice: 50,
    priceCurrency: 'LEAD',
    upgradeLevels: 1,
    unlockedByDefault: false,
  },
};

export function getPowerUpDefinition(id: string): PowerUpDefinition {
  return POWER_UP_CATALOGUE[id] || POWER_UP_CATALOGUE['speed_boost'];
}

export function getAllPowerUps(): PowerUpDefinition[] {
  return Object.values(POWER_UP_CATALOGUE);
}
